[tool.poetry]
name = "ctxfy"
version = "0.1.0"
description = "CLI tool that transforms business requirements into high-quality code"
authors = ["Fernando Jr <contato@fernandojr.dev>"]

[tool.poetry.dependencies]
python = "^3.13"
pydantic-settings = "^2.11"
sqlalchemy = {version = "^2.0", extras = ["asyncio"]}

[tool.poetry.group.dev.dependencies]
ruff = "^0.14"
mypy = "^1.18"
pytest = "^8.4"
pytest-cov = "^7.0"
bandit = "^1.8"
safety = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"